_commit: 0.4.1-46-gc83231c
_src_path: /home/ahal/dev/reps
author: Mozilla Release Engineering <release+test@mozilla.com>
github_slug: mozilla-releng/test
level: 3
min_python_version: '3.10'
package_name: test
project_name: test
project_vcs: jj
short_description: ''
trust_domain: mozilla
