---
trust-domain: "mozilla"
task-priority: low

taskgraph:
  cached-task-prefix: "mozilla.v2.firefox-ci-playground"
  repositories:
    haiku_generator:
      name: "Haiku Generator"

workers:
  aliases:
    images:
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
    linux:
      provisioner: '{trust-domain}-t'
      implementation: docker-worker
      os: linux
      worker-type: 't-{alias}-large-gcp'
