---
trust-domain: "mozilla"
task-priority: low

taskgraph:
  cached-task-prefix: "mozilla.v2.firefox-ci-template"
  repositories:
    firefox_ci_template:
      name: "firefox-ci-template"

workers:
  aliases:
    b-linux:
      provisioner: 'gecko-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
    images:
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
    t-linux-large:
      provisioner: 'gecko-t'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
